export const WORKSPACE_RUNNER_HEALTH_PROBE_TIMEOUT_SECONDS = 5;
export const WORKSPACE_RUNNER_HEALTH_PROBE_TIMEOUT_MS =
  WORKSPACE_RUNNER_HEALTH_PROBE_TIMEOUT_SECONDS * 1000;

export const WORKSPACE_RUNNER_RECOVERY_GRACE_SECONDS = 30;
export const WORKSPACE_RUNNER_RECOVERY_GRACE_MS =
  WORKSPACE_RUNNER_RECOVERY_GRACE_SECONDS * 1000;

export const WORKSPACE_RUNNER_RECOVERY_STOP_TIMEOUT_SECONDS = 10;
export const WORKSPACE_RUNNER_RECOVERY_STOP_TIMEOUT_MS =
  WORKSPACE_RUNNER_RECOVERY_STOP_TIMEOUT_SECONDS * 1000;

export const WORKSPACE_RUNNER_STARTUP_TIMEOUT_SECONDS = 300;
export const WORKSPACE_RUNNER_STARTUP_TIMEOUT_MS =
  WORKSPACE_RUNNER_STARTUP_TIMEOUT_SECONDS * 1000;

export const WORKSPACE_MACHINE_HEALTH_TIMEOUT_SECONDS = 360;
export const WORKSPACE_MACHINE_HEALTH_TIMEOUT_MS =
  WORKSPACE_MACHINE_HEALTH_TIMEOUT_SECONDS * 1000;

export const WORKSPACE_EXECUTION_ACTIVATION_TIMEOUT_SECONDS = 420;
export const WORKSPACE_EXECUTION_ACTIVATION_TIMEOUT_MS =
  WORKSPACE_EXECUTION_ACTIVATION_TIMEOUT_SECONDS * 1000;

/** @deprecated Use the timeout owned by the relevant readiness layer. */
export const WORKSPACE_READINESS_TIMEOUT_SECONDS = 120;
/** @deprecated Use the timeout owned by the relevant readiness layer. */
export const WORKSPACE_READINESS_TIMEOUT_MS =
  WORKSPACE_READINESS_TIMEOUT_SECONDS * 1000;
