import type { RegisteredPageSpec } from "@/lib/types";

const curatedPages: RegisteredPageSpec[] = [
  {
    slug: [],
    filePath: "docs/home.mdx",
    sourceRefs: ["README.md"],
    includeInSidebar: true,
    pageKind: "home",
    priority: 100,
    capabilities: ["openai-compatible http", "operator control", "project review", "evaluation", "workspace automation", "cli"],
  },
  { slug: ["docs"], filePath: "docs/index.mdx", sourceRefs: ["docs/index.md"], includeInSidebar: true, pageKind: "landing", priority: 70 },
  {
    slug: ["docs", "quickstart"],
    filePath: "docs/quickstart.mdx",
    sourceRefs: ["README.md"],
    related: ["docs/core-concepts", "apps/web", "cli/command-suite"],
  },
  {
    slug: ["docs", "core-concepts"],
    filePath: "docs/core-concepts.mdx",
    sourceRefs: ["DESIGN.md", "ARCHITECTURE.md"],
    related: ["docs/runtime-model", "runtime", "reference/terminology"],
  },
  {
    slug: ["docs", "why-kestrel"],
    filePath: "docs/why-kestrel.mdx",
    sourceRefs: ["README.md", "DESIGN.md", "docs/cli/workspaces.md"],
    related: ["docs/core-concepts", "build/building-your-first-agent", "build/workspaces-and-automation"],
    pageKind: "narrative",
    priority: 98,
    capabilities: ["workspace automation", "operator control", "evaluation"],
  },
  {
    slug: ["docs", "architecture-overview"],
    filePath: "docs/architecture-overview.mdx",
    sourceRefs: ["ARCHITECTURE.md", "README.md"],
    related: ["docs/runtime-model", "runtime", "runtime/store-and-replay"],
  },
  {
    slug: ["docs", "runtime-model"],
    filePath: "docs/runtime-model.mdx",
    sourceRefs: ["ARCHITECTURE.md", "RELIABILITY.md", "docs/integrations/nextjs-runner-service.md"],
    related: ["runtime/engine", "runtime/store-and-replay", "deploy/running-the-runner-service"],
    pageKind: "narrative",
    priority: 84,
    capabilities: ["runtime", "runner service", "operator control", "evaluation"],
  },
  {
    slug: ["docs", "faq"],
    filePath: "docs/faq.mdx",
    sourceRefs: ["README.md", "docs/cli/workspaces.md", "docs/integrations/sdk-installation.md"],
    related: ["build/workspaces-and-automation", "deploy", "packages/sdk"],
    pageKind: "reference",
    priority: 78,
    capabilities: ["openai-compatible http", "workspace automation", "operator control", "project review", "evaluation"],
  },
  { slug: ["build"], filePath: "build/index.mdx", sourceRefs: ["packages/sdk/README.md", "docs/integrations/sdk-installation.md"], includeInSidebar: true, pageKind: "landing", priority: 76 },
  {
    slug: ["build", "workspace-copilot-demo"],
    filePath: "build/workspace-copilot-demo.mdx",
    sourceRefs: ["packages/sdk/README.md", "packages/next/README.md", "docs/cli/workspaces.md", "docs/integrations/nextjs-runner-service.md"],
    related: ["build/building-your-first-agent", "build/integrating-with-nextjs", "build/workspaces-and-automation"],
    pageKind: "tutorial",
    priority: 94,
    capabilities: ["workspace automation", "runner service"],
  },
  {
    slug: ["build", "building-your-first-agent"],
    filePath: "build/building-your-first-agent.mdx",
    sourceRefs: ["packages/sdk/README.md", "packages/sdk/src/agent.ts", "docs/integrations/sdk-installation.md"],
    related: ["build/workspace-copilot-demo", "build/running-your-first-streamed-request", "packages/sdk"],
    pageKind: "tutorial",
    priority: 96,
  },
  {
    slug: ["build", "running-your-first-streamed-request"],
    filePath: "build/running-your-first-streamed-request.mdx",
    sourceRefs: ["packages/sdk/README.md", "packages/sdk/src/agent.ts"],
    related: ["build/building-your-first-agent", "build/adding-background-subscriptions", "packages/sdk"],
    pageKind: "tutorial",
    priority: 89,
  },
  {
    slug: ["build", "adding-session-memory"],
    filePath: "build/adding-session-memory.mdx",
    sourceRefs: ["packages/sdk/README.md", "packages/sdk/src/agent.ts"],
    related: ["build/building-your-first-agent", "build/automating-common-tasks", "packages/sdk"],
    pageKind: "tutorial",
    priority: 87,
    capabilities: ["workspace automation"],
  },
  {
    slug: ["build", "adding-background-subscriptions"],
    filePath: "build/adding-background-subscriptions.mdx",
    sourceRefs: ["packages/sdk/README.md", "packages/sdk/src/agent.ts"],
    related: ["build/running-your-first-streamed-request", "packages/sdk", "packages/observability"],
    pageKind: "tutorial",
    priority: 83,
  },
  {
    slug: ["build", "integrating-with-nextjs"],
    filePath: "build/integrating-with-nextjs.mdx",
    sourceRefs: ["packages/next/README.md", "packages/next/src/routes.ts", "docs/integrations/nextjs-runner-service.md"],
    related: ["build/workspace-copilot-demo", "build/nextjs-route-cookbook", "deploy/running-the-runner-service", "packages/next"],
    pageKind: "tutorial",
    priority: 95,
    capabilities: ["nextjs", "runner service"],
  },
  {
    slug: ["build", "nextjs-route-cookbook"],
    filePath: "build/nextjs-route-cookbook.mdx",
    sourceRefs: ["packages/next/src/routes.ts", "docs/integrations/nextjs-runner-service.md"],
    related: ["build/integrating-with-nextjs", "packages/next", "deploy/environment-and-auth"],
    pageKind: "reference",
    priority: 86,
    capabilities: ["nextjs", "runner service"],
  },
  {
    slug: ["build", "openai-compatible-http"],
    filePath: "build/openai-compatible-http.mdx",
    sourceRefs: ["docs/integrations/nextjs-runner-service.md", "tests/integration/runner-service-openai-compat.test.ts"],
    related: ["build/integrating-with-nextjs", "packages/next", "packages/sdk"],
    pageKind: "tutorial",
    priority: 97,
    capabilities: ["openai-compatible http", "runner service"],
  },
  {
    slug: ["build", "adding-observability"],
    filePath: "build/adding-observability.mdx",
    sourceRefs: ["packages/observability/README.md", "packages/observability/src/tracer.ts", "packages/observability/src/otel.ts"],
    related: ["packages/observability", "build/building-your-first-agent", "operations/reliability"],
    pageKind: "tutorial",
    priority: 80,
  },
  {
    slug: ["build", "workspaces-and-automation"],
    filePath: "build/workspaces-and-automation.mdx",
    sourceRefs: ["docs/cli/workspaces.md", "cli/workspace/WorkspaceResolver.ts", "cli/workspace/WorkspaceStore.ts"],
    related: ["build/workspace-copilot-demo", "build/automating-common-tasks", "cli/workspace-workflows"],
    pageKind: "tutorial",
    priority: 92,
    capabilities: ["workspace automation"],
  },
  {
    slug: ["build", "automating-common-tasks"],
    filePath: "build/automating-common-tasks.mdx",
    sourceRefs: ["docs/cli/workspaces.md", "cli/kcron.ts"],
    related: ["build/workspaces-and-automation", "cli/kcron", "deploy/production-operating-model"],
    pageKind: "tutorial",
    priority: 90,
    capabilities: ["workspace automation"],
  },
  { slug: ["deploy"], filePath: "deploy/index.mdx", sourceRefs: ["docs/integrations/nextjs-runner-service.md", "cli/webCommand.ts"], includeInSidebar: true, pageKind: "landing", priority: 74 },
  {
    slug: ["deploy", "running-the-runner-service"],
    filePath: "deploy/running-the-runner-service.mdx",
    sourceRefs: ["docs/integrations/nextjs-runner-service.md", "cli/webCommand.ts"],
    related: ["build/workspace-copilot-demo", "deploy/environment-and-auth", "build/integrating-with-nextjs"],
    pageKind: "tutorial",
    priority: 88,
    capabilities: ["runner service"],
  },
  {
    slug: ["deploy", "environment-and-auth"],
    filePath: "deploy/environment-and-auth.mdx",
    sourceRefs: ["docs/integrations/nextjs-runner-service.md", "README.md"],
    related: ["deploy/running-the-runner-service", "build/building-your-first-agent", "packages/next"],
    pageKind: "tutorial",
    priority: 82,
    capabilities: ["runner service"],
  },
  {
    slug: ["deploy", "production-operating-model"],
    filePath: "deploy/production-operating-model.mdx",
    sourceRefs: ["ARCHITECTURE.md", "RELIABILITY.md", "docs/cli/workspaces.md"],
    related: ["operations/reliability", "runtime/store-and-replay", "build/automating-common-tasks"],
    pageKind: "reference",
    priority: 77,
    capabilities: ["runner service", "workspace automation"],
  },
  {
    slug: ["deploy", "deployment-troubleshooting"],
    filePath: "deploy/deployment-troubleshooting.mdx",
    sourceRefs: ["docs/integrations/nextjs-runner-service.md", "docs/cli/workspaces.md", "README.md"],
    related: ["deploy/running-the-runner-service", "deploy/environment-and-auth", "operations/reliability"],
    pageKind: "reference",
    priority: 79,
    capabilities: ["runner service"],
  },
  { slug: ["apps"], filePath: "apps/index.mdx", includeInSidebar: true, pageKind: "landing", priority: 72 },
  {
    slug: ["apps", "web"],
    filePath: "apps/web.mdx",
    sourceRefs: ["README.md", "apps/web/package.json"],
    related: ["build/integrating-with-nextjs", "deploy/running-the-runner-service", "packages/next"],
    pageKind: "reference",
    priority: 82,
    capabilities: ["operator control", "project review", "task graph", "project snapshot"],
  },
  {
    slug: ["apps", "desktop"],
    filePath: "apps/desktop.mdx",
    sourceRefs: ["apps/desktop/package.json", "apps/desktop/src/main.ts"],
    related: ["build/workspaces-and-automation", "cli/kchat", "cli/workspace-workflows"],
    pageKind: "reference",
    priority: 76,
    capabilities: ["cli", "workspace automation"],
  },
  { slug: ["packages"], filePath: "packages/index.mdx", includeInSidebar: true, pageKind: "landing", priority: 73 },
  {
    slug: ["packages", "sdk"],
    filePath: "packages/sdk.mdx",
    sourceRefs: ["packages/sdk/README.md", "packages/sdk/src/agent.ts"],
    related: ["build/building-your-first-agent", "packages/next", "operations/review-and-state-workflows", "packages/observability"],
    pageKind: "reference",
    priority: 95,
    capabilities: ["operator control", "project review", "task graph", "project snapshot", "workspace automation"],
  },
  {
    slug: ["packages", "next"],
    filePath: "packages/next.mdx",
    sourceRefs: ["packages/next/README.md", "docs/integrations/nextjs-runner-service.md"],
    related: ["build/integrating-with-nextjs", "deploy/running-the-runner-service", "packages/sdk"],
    pageKind: "reference",
    priority: 85,
    capabilities: ["nextjs", "openai-compatible http", "runner service"],
  },
  {
    slug: ["packages", "observability"],
    filePath: "packages/observability.mdx",
    sourceRefs: ["packages/observability/README.md", "packages/observability/src/tracer.ts", "packages/observability/src/otel.ts"],
    related: ["build/adding-observability", "operations/reliability", "runtime/store-and-replay"],
    pageKind: "reference",
    priority: 72,
  },
  { slug: ["cli"], filePath: "cli/index.mdx", includeInSidebar: true, pageKind: "landing", priority: 75 },
  {
    slug: ["cli", "command-suite"],
    filePath: "cli/command-suite.mdx",
    sourceRefs: ["README.md", "docs/cli/kchat.md"],
    related: ["cli", "cli/workspace-workflows", "cli/runner-service"],
    pageKind: "reference",
    priority: 78,
    capabilities: ["cli", "workspace automation"],
  },
  {
    slug: ["cli", "kchat"],
    filePath: "cli/kchat.mdx",
    sourceRefs: ["docs/cli/kchat.md", "docs/cli/kchat-protocol.md"],
    related: ["cli/command-suite", "cli/profiles-code-mode-and-mcp", "operations/operator-control-workflows", "apps/desktop"],
    pageKind: "reference",
    priority: 96,
    capabilities: ["cli", "operator control"],
  },
  {
    slug: ["cli", "kcron"],
    filePath: "cli/kcron.mdx",
    sourceRefs: ["docs/cli/workspaces.md", "cli/kcron.ts"],
    related: ["cli/workspace-workflows", "apps/desktop", "operations/reliability"],
    pageKind: "reference",
    priority: 84,
    capabilities: ["workspace automation"],
  },
  {
    slug: ["cli", "workspace-workflows"],
    filePath: "cli/workspace-workflows.mdx",
    sourceRefs: ["docs/cli/workspaces.md"],
    related: ["build/workspaces-and-automation", "build/automating-common-tasks", "cli/kcron"],
    pageKind: "reference",
    priority: 88,
    capabilities: ["workspace automation"],
  },
  {
    slug: ["cli", "runner-service"],
    filePath: "cli/runner-service.mdx",
    sourceRefs: ["docs/integrations/nextjs-runner-service.md", "cli/webCommand.ts"],
    related: ["deploy/running-the-runner-service", "build/integrating-with-nextjs", "apps/web"],
    pageKind: "reference",
    priority: 87,
    capabilities: ["runner service"],
  },
  {
    slug: ["cli", "profiles-code-mode-and-mcp"],
    filePath: "cli/profiles-code-mode-and-mcp.mdx",
    sourceRefs: ["docs/cli/kchat.md", "cli/config/ProfileStore.ts", "cli/app/App.ts"],
    related: ["cli/kchat", "build/workspaces-and-automation", "packages/sdk"],
    pageKind: "reference",
    priority: 90,
    capabilities: ["profiles, code mode, and mcp", "workspace automation"],
  },
  {
    slug: ["runtime"],
    filePath: "runtime/index.mdx",
    sourceRefs: ["ARCHITECTURE.md", "DESIGN.md"],
    includeInSidebar: true,
    pageKind: "landing",
    priority: 71,
    capabilities: ["runtime"],
  },
  {
    slug: ["runtime", "engine"],
    filePath: "runtime/engine.mdx",
    sourceRefs: ["ARCHITECTURE.md"],
    related: ["runtime/io-and-tools", "runtime/store-and-replay", "reference/terminology"],
    pageKind: "reference",
    priority: 69,
    capabilities: ["runtime", "runner service"],
  },
  {
    slug: ["runtime", "io-and-tools"],
    filePath: "runtime/io-and-tools.mdx",
    sourceRefs: ["ARCHITECTURE.md", "docs/references/heuristic-hotspots.md"],
    related: ["runtime/engine", "cli/runner-service", "reference/heuristic-hotspots"],
    pageKind: "reference",
    priority: 67,
    capabilities: ["runtime"],
  },
  {
    slug: ["runtime", "store-and-replay"],
    filePath: "runtime/store-and-replay.mdx",
    sourceRefs: ["ARCHITECTURE.md", "RELIABILITY.md"],
    related: ["operations/evaluations", "operations/reliability", "reference/quality-score"],
    pageKind: "reference",
    priority: 93,
    capabilities: ["runtime", "evaluation"],
  },
  {
    slug: ["runtime", "governance-and-invariants"],
    filePath: "runtime/governance-and-invariants.mdx",
    sourceRefs: ["AGENTS.md", "docs/references/lint-invariants.md", "docs/references/heuristic-hotspots.md"],
    related: ["reference/lint-invariants", "reference/heuristic-hotspots", "operations/quality-gates"],
    internal: true,
  },
  { slug: ["operations"], filePath: "operations/index.mdx", sourceRefs: ["RELIABILITY.md", "SECURITY.md", "QUALITY_SCORE.md"], includeInSidebar: true, pageKind: "landing", priority: 79 },
  {
    slug: ["operations", "reliability"],
    filePath: "operations/reliability.mdx",
    sourceRefs: ["RELIABILITY.md"],
    related: ["operations/evaluations", "operations/quality-gates", "archive"],
    pageKind: "reference",
    priority: 74,
  },
  {
    slug: ["operations", "security"],
    filePath: "operations/security.mdx",
    sourceRefs: ["SECURITY.md"],
    related: ["runtime/governance-and-invariants", "reference/architecture-rules", "reference/lint-invariants"],
    pageKind: "reference",
    priority: 64,
  },
  {
    slug: ["operations", "migration"],
    filePath: "operations/migration.mdx",
    sourceRefs: ["README.md", "docs/runbooks/2026-02-26-v3-migration-runbook.md"],
    related: ["operations/reliability", "archive", "runtime/store-and-replay"],
    pageKind: "reference",
    priority: 58,
  },
  {
    slug: ["operations", "prompt-suite"],
    filePath: "operations/prompt-suite.mdx",
    sourceRefs: ["README.md"],
    related: ["operations/quality-gates", "runtime/governance-and-invariants", "reference/quality-score"],
    pageKind: "reference",
    priority: 62,
  },
  {
    slug: ["operations", "evaluations"],
    filePath: "operations/evaluations.mdx",
    sourceRefs: ["evals/README.md", "evals/migration/ownership-ledger.json"],
    related: ["operations/quality-gates", "runtime/store-and-replay", "archive"],
    pageKind: "reference",
    priority: 91,
    capabilities: ["evaluation"],
  },
  {
    slug: ["operations", "quality-gates"],
    filePath: "operations/quality-gates.mdx",
    sourceRefs: ["QUALITY_SCORE.md", "docs/references/lint-invariants.md"],
    related: ["operations/prompt-suite", "operations/artifact-inspection", "reference/quality-score", "runtime/governance-and-invariants"],
    pageKind: "reference",
    priority: 66,
  },
  {
    slug: ["operations", "artifact-inspection"],
    filePath: "operations/artifact-inspection.mdx",
    sourceRefs: ["docs/cli/workspaces.md", "README.md", "RELIABILITY.md"],
    related: ["operations/reliability", "runtime/store-and-replay", "build/workspace-copilot-demo"],
    pageKind: "reference",
    priority: 89,
    capabilities: ["artifact inspection", "evaluation", "workspace automation"],
  },
  {
    slug: ["operations", "operator-control-workflows"],
    filePath: "operations/operator-control-workflows.mdx",
    sourceRefs: ["docs/integrations/nextjs-runner-service.md", "docs/cli/kchat.md", "packages/sdk/src/KestrelClient.ts"],
    related: ["cli/kchat", "apps/web", "operations/review-and-state-workflows", "packages/sdk"],
    pageKind: "reference",
    priority: 93,
    capabilities: ["operator control"],
  },
  {
    slug: ["operations", "review-and-state-workflows"],
    filePath: "operations/review-and-state-workflows.mdx",
    sourceRefs: ["apps/web/lib/client/stateSync.ts", "apps/web/tests/routes.test.ts", "packages/sdk/src/KestrelClient.ts"],
    related: ["operations/operator-control-workflows", "apps/web", "packages/sdk"],
    pageKind: "reference",
    priority: 99,
    capabilities: ["project review", "task graph", "project snapshot"],
  },
  { slug: ["reference"], filePath: "reference/index.mdx", sourceRefs: ["docs/index.md"], includeInSidebar: true, pageKind: "landing", priority: 68 },
  {
    slug: ["reference", "terminology"],
    filePath: "reference/terminology.mdx",
    sourceRefs: ["README.md", "ARCHITECTURE.md"],
    related: ["docs/core-concepts", "runtime/engine", "apps/web"],
  },
  {
    slug: ["reference", "architecture-rules"],
    filePath: "reference/architecture-rules.mdx",
    sourceRefs: ["docs/references/architecture-rules.json"],
    related: ["runtime/governance-and-invariants", "operations/security", "reference/lint-invariants"],
    internal: true,
  },
  {
    slug: ["reference", "release-tracks"],
    filePath: "reference/release-tracks.mdx",
    sourceRefs: ["docs/references/release-tracks.json"],
    related: ["reference/quality-score", "operations/quality-gates", "archive"],
    internal: true,
  },
  {
    slug: ["reference", "quality-score"],
    filePath: "reference/quality-score.mdx",
    sourceRefs: ["QUALITY_SCORE.md", "docs/generated/quality-scorecard.json"],
    related: ["operations/quality-gates", "operations/reliability", "reference/release-tracks"],
    internal: true,
  },
  {
    slug: ["reference", "heuristic-hotspots"],
    filePath: "reference/heuristic-hotspots.mdx",
    sourceRefs: ["docs/references/heuristic-hotspots.md"],
    related: ["runtime/governance-and-invariants", "reference/lint-invariants", "operations/security"],
    internal: true,
  },
  {
    slug: ["reference", "lint-invariants"],
    filePath: "reference/lint-invariants.mdx",
    sourceRefs: ["docs/references/lint-invariants.md"],
    related: ["runtime/governance-and-invariants", "reference/architecture-rules", "operations/quality-gates"],
    internal: true,
  },
  { slug: ["archive"], filePath: "archive/index.mdx", sourceRefs: ["docs/PLANS.md"], includeInSidebar: true, pageKind: "landing", priority: 20 },
];

const archivedPlans: RegisteredPageSpec[] = [
  "2026-04-20-desktop-project-library-persistence-design",
  "2026-04-20-thread-titlebar-icon-first-design",
  "2026-04-20-thread-titlebar-icon-first-implementation-plan",
  "2026-04-27-terminal-bench-dual-adapter-design",
  "2026-04-28-terminal-bench-task-queue-improvement-loop-design",
  "2026-05-11-terminal-bench-completion-boundary-hardening",
  "2026-05-13-composer-multimodal-followups-design",
  "2026-05-14-reference-react-command-processor-milestones",
].map((slug) => ({
  slug: ["archive", "plans", slug],
  sourcePath: `docs/plans/${slug}.md`,
  archive: true,
  archiveGroup: "plans" as const,
}));

const archivedRunbooks: RegisteredPageSpec[] = [
  "2026-02-25-kestrel-mvp-operator-runbook",
  "2026-02-26-v3-migration-runbook",
].map((slug) => ({
  slug: ["archive", "runbooks", slug],
  sourcePath: `docs/runbooks/${slug}.md`,
  archive: true,
  archiveGroup: "runbooks" as const,
}));

export const pageRegistry = [...curatedPages, ...archivedPlans, ...archivedRunbooks];

const slugSet = new Set<string>();
for (const spec of pageRegistry) {
  const key = spec.slug.join("/");
  if (slugSet.has(key)) {
    throw new Error(`Duplicate docs slug registered: '${key || "/"}'.`);
  }
  slugSet.add(key);
}

export function findPageSpec(slug: string[]) {
  return pageRegistry.find((spec) => spec.slug.length === slug.length && spec.slug.every((segment, index) => segment === slug[index])) ?? null;
}
