export const DOCS_RELEASE = {
  packages: {
    version: "0.8.0",
    line: "0.8",
    channel: "Stable",
    releasedPackageNames: [
      "@kestrel-agents/kestrel",
      "@kestrel-agents/protocol",
      "@kestrel-agents/sdk",
      "@kestrel-agents/memory",
      "@kestrel-agents/next",
      "@kestrel-agents/ai-sdk",
      "@kestrel-agents/observability",
      "@kestrel-agents/workspace-skills",
    ],
    releaseNotesUrl: "/reference/releases",
  },
  products: {
    cli: {
      version: "0.8.0",
      channel: "Stable",
      mode: "npm-and-archive",
      installCommand: "npm install -g @kestrel-agents/kestrel@0.8.0",
      releasesUrl: "https://github.com/LumiCorp/kestrel/releases/tag/v0.8.0",
      archiveUrl: "https://github.com/LumiCorp/kestrel/releases/download/v0.8.0/kestrel-cli-0.8.0-darwin-arm64.tar.gz",
      supportedPlatforms: ["macOS arm64", "Linux x64"],
      runtimeRequirement: "Node.js 22",
    },
    desktop: {
      version: "0.8.0",
      channel: "Beta",
      mode: "manual-download",
      releasesUrl: "https://github.com/LumiCorp/kestrel/releases/tag/v0.8.0",
      downloadUrl: "https://github.com/LumiCorp/kestrel/releases/download/v0.8.0/Kestrel-0.8.0-mac-arm64.dmg",
      artifactStatus: "release-gated",
      supportedPlatforms: ["macOS 13+ on Apple silicon"],
      trustNote: "Download the signed and notarized DMG. Kestrel 0.8.0 is a manual install and does not move the stable OTA pointer.",
    },
    kestrelOne: {
      version: "0.8.0",
      channel: "Beta",
      mode: "source-and-hosted",
      sourceUrl: "https://github.com/LumiCorp/kestrel/tree/v0.8.0/apps/web",
      hostedAccess: "Invitation",
      accessNote: "Kestrel One 0.8.0 source is available from the release tag. The Lumi-hosted service remains available to invited teams.",
    },
  },
  compatibility: [
    { surface: "Runtime", version: "0.8.0", channel: "Stable", note: "Owns execution, recovery, evaluation, budgets, and the runner service" },
    { surface: "Protocol", version: "0.8.0", channel: "Stable", note: "Owns execution, conversations, approvals, recovery, Mission Control, and events" },
    { surface: "SDK", version: "0.8.0", channel: "Stable", note: "Consumes the exact matching runner and protocol contracts" },
    { surface: "Memory", version: "0.8.0", channel: "Stable", note: "Provides governed memory contracts, backends, and retrieval helpers" },
    { surface: "Next.js", version: "0.8.0", channel: "Stable", note: "Adapts SDK results to server routes" },
    { surface: "AI SDK", version: "0.8.0", channel: "Stable", note: "Adapts runner streams to AI SDK presentation events" },
    { surface: "Observability", version: "0.8.0", channel: "Stable", note: "Carries compatible trace context and correlation" },
    { surface: "Workspace skills", version: "0.8.0", channel: "Stable", note: "Installs and verifies portable workspace guidance" },
    { surface: "CLI", version: "0.8.0", channel: "Stable", note: "Supports macOS arm64 and Linux x64 on Node.js 22" },
    { surface: "Desktop", version: "0.8.0", channel: "Beta", note: "Signed, notarized, manual-install macOS arm64 application" },
    { surface: "Kestrel One", version: "0.8.0", channel: "Beta", note: "Versioned source plus an invitation-only Lumi-hosted deployment" },
  ],
} as const;

export const DOCS_RELEASE_LABEL = `${DOCS_RELEASE.packages.version} ${DOCS_RELEASE.packages.channel}`;
