export const PALETTE_STORAGE_KEY = "kestrel-one.palette-preferences.v1";

export const PALETTE_IDS = [
  "lumi",
  "graphite",
  "harbor",
  "juniper",
  "ember",
  "iris",
] as const;

export type PaletteId = (typeof PALETTE_IDS)[number];
export type PaletteMode = "light" | "dark";

export const PALETTE_TOKEN_NAMES = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "border",
  "input",
  "ring",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "sidebar",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
  "secondary-offset",
  "surface",
  "surface-foreground",
  "code",
  "code-foreground",
  "code-highlight",
  "code-number",
  "selection",
  "selection-foreground",
  "message-user",
  "message-user-foreground",
] as const;

export type PaletteTokenName = (typeof PALETTE_TOKEN_NAMES)[number];
export type PaletteTokens = Record<PaletteTokenName, string>;

export type PaletteFamily = {
  id: PaletteId;
  label: string;
  description: string;
  light: PaletteTokens;
  dark: PaletteTokens;
};

export type PalettePreferences = {
  light: PaletteId;
  dark: PaletteId;
};

export const DEFAULT_PALETTE_PREFERENCES: PalettePreferences = {
  light: "lumi",
  dark: "lumi",
};

const lumiLight: PaletteTokens = {
  background: "#fffdf7",
  foreground: "#111111",
  card: "#f7f3e8",
  "card-foreground": "#111111",
  popover: "#fffdf7",
  "popover-foreground": "#111111",
  primary: "#c77738",
  "primary-foreground": "#111111",
  secondary: "#f1ece1",
  "secondary-foreground": "#111111",
  muted: "#efe7da",
  "muted-foreground": "#5c564d",
  accent: "#5e8fa0",
  "accent-foreground": "#111111",
  destructive: "#a33f2b",
  border: "#ddd5c7",
  input: "#ddd5c7",
  ring: "#5e8fa0",
  "chart-1": "#c77738",
  "chart-2": "#5e8fa0",
  "chart-3": "#8b5b3a",
  "chart-4": "#8eb0bb",
  "chart-5": "#d59664",
  sidebar: "#fbf7ef",
  "sidebar-foreground": "#111111",
  "sidebar-primary": "#c77738",
  "sidebar-primary-foreground": "#111111",
  "sidebar-accent": "#e8efe9",
  "sidebar-accent-foreground": "#111111",
  "sidebar-border": "#ddd5c7",
  "sidebar-ring": "#5e8fa0",
  "secondary-offset": "#fcf8ef",
  surface: "#fcf8ef",
  "surface-foreground": "#111111",
  code: "#fcf8ef",
  "code-foreground": "#111111",
  "code-highlight": "#f1ece1",
  "code-number": "#8b4b1d",
  selection: "#111111",
  "selection-foreground": "#fffdf7",
  "message-user": "#005bd6",
  "message-user-foreground": "#ffffff",
};

const lumiDark: PaletteTokens = {
  background: "#111111",
  foreground: "#f7f3e8",
  card: "#181818",
  "card-foreground": "#f7f3e8",
  popover: "#151515",
  "popover-foreground": "#f7f3e8",
  primary: "#c77738",
  "primary-foreground": "#111111",
  secondary: "#202020",
  "secondary-foreground": "#f7f3e8",
  muted: "#232323",
  "muted-foreground": "#c8bfb0",
  accent: "#8eb0bb",
  "accent-foreground": "#111111",
  destructive: "#d07a4a",
  border: "#34312e",
  input: "#3c3834",
  ring: "#8eb0bb",
  "chart-1": "#d59664",
  "chart-2": "#8eb0bb",
  "chart-3": "#f7f3e8",
  "chart-4": "#6e98a7",
  "chart-5": "#b96a30",
  sidebar: "#171717",
  "sidebar-foreground": "#f7f3e8",
  "sidebar-primary": "#c77738",
  "sidebar-primary-foreground": "#111111",
  "sidebar-accent": "#202425",
  "sidebar-accent-foreground": "#f7f3e8",
  "sidebar-border": "#34312e",
  "sidebar-ring": "#8eb0bb",
  "secondary-offset": "#1a1a1a",
  surface: "#1a1a1a",
  "surface-foreground": "#d8cebf",
  code: "#1a1a1a",
  "code-foreground": "#d8cebf",
  "code-highlight": "#242424",
  "code-number": "#d59664",
  selection: "#f7f3e8",
  "selection-foreground": "#111111",
  "message-user": "#2869d8",
  "message-user-foreground": "#ffffff",
};

const graphiteLight: PaletteTokens = {
  background: "#fafafa",
  foreground: "#17191c",
  card: "#f1f3f5",
  "card-foreground": "#17191c",
  popover: "#ffffff",
  "popover-foreground": "#17191c",
  primary: "#405f78",
  "primary-foreground": "#ffffff",
  secondary: "#e8ebee",
  "secondary-foreground": "#20252a",
  muted: "#e9ecef",
  "muted-foreground": "#505860",
  accent: "#54768a",
  "accent-foreground": "#ffffff",
  destructive: "#a43d42",
  border: "#cfd4d8",
  input: "#c7cdd2",
  ring: "#54768a",
  "chart-1": "#405f78",
  "chart-2": "#6d8799",
  "chart-3": "#363c43",
  "chart-4": "#8ba0ad",
  "chart-5": "#74808a",
  sidebar: "#f4f5f6",
  "sidebar-foreground": "#17191c",
  "sidebar-primary": "#405f78",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#e4e9ed",
  "sidebar-accent-foreground": "#17191c",
  "sidebar-border": "#cfd4d8",
  "sidebar-ring": "#54768a",
  "secondary-offset": "#f7f8f9",
  surface: "#f7f8f9",
  "surface-foreground": "#20252a",
  code: "#f3f5f6",
  "code-foreground": "#20252a",
  "code-highlight": "#e5e9ec",
  "code-number": "#405f78",
  selection: "#293640",
  "selection-foreground": "#ffffff",
  "message-user": "#405f78",
  "message-user-foreground": "#ffffff",
};

const graphiteDark: PaletteTokens = {
  background: "#121416",
  foreground: "#f4f6f8",
  card: "#1a1d20",
  "card-foreground": "#f4f6f8",
  popover: "#171a1d",
  "popover-foreground": "#f4f6f8",
  primary: "#9bbbd2",
  "primary-foreground": "#121416",
  secondary: "#24282c",
  "secondary-foreground": "#f4f6f8",
  muted: "#252a2e",
  "muted-foreground": "#b9c1c8",
  accent: "#86aebe",
  "accent-foreground": "#121416",
  destructive: "#df777b",
  border: "#353b40",
  input: "#3c4349",
  ring: "#86aebe",
  "chart-1": "#9bbbd2",
  "chart-2": "#86aebe",
  "chart-3": "#d7dde2",
  "chart-4": "#708b9d",
  "chart-5": "#a0aab2",
  sidebar: "#171a1c",
  "sidebar-foreground": "#f4f6f8",
  "sidebar-primary": "#9bbbd2",
  "sidebar-primary-foreground": "#121416",
  "sidebar-accent": "#252b2f",
  "sidebar-accent-foreground": "#f4f6f8",
  "sidebar-border": "#353b40",
  "sidebar-ring": "#86aebe",
  "secondary-offset": "#181b1e",
  surface: "#181b1e",
  "surface-foreground": "#d5dbe0",
  code: "#181b1e",
  "code-foreground": "#d5dbe0",
  "code-highlight": "#24292d",
  "code-number": "#9bbbd2",
  selection: "#dce5eb",
  "selection-foreground": "#121416",
  "message-user": "#315f7e",
  "message-user-foreground": "#ffffff",
};

const harborLight: PaletteTokens = {
  background: "#f6fafc",
  foreground: "#102333",
  card: "#eaf2f7",
  "card-foreground": "#102333",
  popover: "#fbfdfe",
  "popover-foreground": "#102333",
  primary: "#1f5f8f",
  "primary-foreground": "#ffffff",
  secondary: "#e0edf4",
  "secondary-foreground": "#173247",
  muted: "#e4eef3",
  "muted-foreground": "#496172",
  accent: "#2f746f",
  "accent-foreground": "#ffffff",
  destructive: "#a63f4c",
  border: "#c5d8e3",
  input: "#bdd2de",
  ring: "#2876aa",
  "chart-1": "#1f5f8f",
  "chart-2": "#2f746f",
  "chart-3": "#5e7890",
  "chart-4": "#58a6a0",
  "chart-5": "#70a1c2",
  sidebar: "#edf5f8",
  "sidebar-foreground": "#102333",
  "sidebar-primary": "#1f5f8f",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#dceceb",
  "sidebar-accent-foreground": "#102333",
  "sidebar-border": "#c5d8e3",
  "sidebar-ring": "#2876aa",
  "secondary-offset": "#f0f7fa",
  surface: "#f0f7fa",
  "surface-foreground": "#173247",
  code: "#edf5f8",
  "code-foreground": "#173247",
  "code-highlight": "#dceaf1",
  "code-number": "#1f5f8f",
  selection: "#173b55",
  "selection-foreground": "#ffffff",
  "message-user": "#1f5f8f",
  "message-user-foreground": "#ffffff",
};

const harborDark: PaletteTokens = {
  background: "#0d1721",
  foreground: "#edf6fb",
  card: "#132230",
  "card-foreground": "#edf6fb",
  popover: "#101d29",
  "popover-foreground": "#edf6fb",
  primary: "#78b9e8",
  "primary-foreground": "#0d1721",
  secondary: "#1a2b39",
  "secondary-foreground": "#edf6fb",
  muted: "#1c3040",
  "muted-foreground": "#b4cad8",
  accent: "#6bc7c0",
  "accent-foreground": "#0d1721",
  destructive: "#e27b86",
  border: "#294052",
  input: "#304a5e",
  ring: "#78b9e8",
  "chart-1": "#78b9e8",
  "chart-2": "#6bc7c0",
  "chart-3": "#b6d8ee",
  "chart-4": "#5e92b8",
  "chart-5": "#85a6bc",
  sidebar: "#101d28",
  "sidebar-foreground": "#edf6fb",
  "sidebar-primary": "#78b9e8",
  "sidebar-primary-foreground": "#0d1721",
  "sidebar-accent": "#19303d",
  "sidebar-accent-foreground": "#edf6fb",
  "sidebar-border": "#294052",
  "sidebar-ring": "#78b9e8",
  "secondary-offset": "#111e29",
  surface: "#111e29",
  "surface-foreground": "#c6dbe7",
  code: "#111e29",
  "code-foreground": "#c6dbe7",
  "code-highlight": "#1b3040",
  "code-number": "#78b9e8",
  selection: "#cceaff",
  "selection-foreground": "#0d1721",
  "message-user": "#246a9e",
  "message-user-foreground": "#ffffff",
};

const juniperLight: PaletteTokens = {
  background: "#f7faf5",
  foreground: "#17251c",
  card: "#ecf3e9",
  "card-foreground": "#17251c",
  popover: "#fbfdf9",
  "popover-foreground": "#17251c",
  primary: "#38694f",
  "primary-foreground": "#ffffff",
  secondary: "#e4ede0",
  "secondary-foreground": "#21372a",
  muted: "#e7eee3",
  "muted-foreground": "#536458",
  accent: "#8a5e18",
  "accent-foreground": "#ffffff",
  destructive: "#a54036",
  border: "#cad8c5",
  input: "#c2d2bc",
  ring: "#477d60",
  "chart-1": "#38694f",
  "chart-2": "#8a5e18",
  "chart-3": "#65815f",
  "chart-4": "#7e9e77",
  "chart-5": "#b4873e",
  sidebar: "#eff5ec",
  "sidebar-foreground": "#17251c",
  "sidebar-primary": "#38694f",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#e3ead7",
  "sidebar-accent-foreground": "#17251c",
  "sidebar-border": "#cad8c5",
  "sidebar-ring": "#477d60",
  "secondary-offset": "#f2f7ef",
  surface: "#f2f7ef",
  "surface-foreground": "#21372a",
  code: "#eff5ec",
  "code-foreground": "#21372a",
  "code-highlight": "#dfe9da",
  "code-number": "#38694f",
  selection: "#234331",
  "selection-foreground": "#ffffff",
  "message-user": "#38694f",
  "message-user-foreground": "#ffffff",
};

const juniperDark: PaletteTokens = {
  background: "#0e1712",
  foreground: "#eef5eb",
  card: "#16221a",
  "card-foreground": "#eef5eb",
  popover: "#121d16",
  "popover-foreground": "#eef5eb",
  primary: "#86c69e",
  "primary-foreground": "#0e1712",
  secondary: "#202d24",
  "secondary-foreground": "#eef5eb",
  muted: "#223127",
  "muted-foreground": "#b9cdbd",
  accent: "#d6ad5c",
  "accent-foreground": "#171207",
  destructive: "#df7c6e",
  border: "#314438",
  input: "#384d3f",
  ring: "#86c69e",
  "chart-1": "#86c69e",
  "chart-2": "#d6ad5c",
  "chart-3": "#c6dec9",
  "chart-4": "#6c9d7d",
  "chart-5": "#a98c51",
  sidebar: "#121d16",
  "sidebar-foreground": "#eef5eb",
  "sidebar-primary": "#86c69e",
  "sidebar-primary-foreground": "#0e1712",
  "sidebar-accent": "#203126",
  "sidebar-accent-foreground": "#eef5eb",
  "sidebar-border": "#314438",
  "sidebar-ring": "#86c69e",
  "secondary-offset": "#121d16",
  surface: "#121d16",
  "surface-foreground": "#c8d8ca",
  code: "#121d16",
  "code-foreground": "#c8d8ca",
  "code-highlight": "#203027",
  "code-number": "#d6ad5c",
  selection: "#d9ecdc",
  "selection-foreground": "#0e1712",
  "message-user": "#2c724e",
  "message-user-foreground": "#ffffff",
};

const emberLight: PaletteTokens = {
  background: "#fff9f3",
  foreground: "#2b1c16",
  card: "#f7ede3",
  "card-foreground": "#2b1c16",
  popover: "#fffaf6",
  "popover-foreground": "#2b1c16",
  primary: "#984426",
  "primary-foreground": "#ffffff",
  secondary: "#f2e5d9",
  "secondary-foreground": "#3b271e",
  muted: "#f1e6dc",
  "muted-foreground": "#6a574e",
  accent: "#486b82",
  "accent-foreground": "#ffffff",
  destructive: "#aa3935",
  border: "#dfcfc1",
  input: "#d9c6b6",
  ring: "#a55334",
  "chart-1": "#984426",
  "chart-2": "#486b82",
  "chart-3": "#7f5d4e",
  "chart-4": "#7f9caf",
  "chart-5": "#c77a57",
  sidebar: "#fbf1e8",
  "sidebar-foreground": "#2b1c16",
  "sidebar-primary": "#984426",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#e7eceb",
  "sidebar-accent-foreground": "#2b1c16",
  "sidebar-border": "#dfcfc1",
  "sidebar-ring": "#a55334",
  "secondary-offset": "#fcf4ec",
  surface: "#fcf4ec",
  "surface-foreground": "#3b271e",
  code: "#f9f0e8",
  "code-foreground": "#3b271e",
  "code-highlight": "#efe0d3",
  "code-number": "#984426",
  selection: "#5a2a1b",
  "selection-foreground": "#ffffff",
  "message-user": "#984426",
  "message-user-foreground": "#ffffff",
};

const emberDark: PaletteTokens = {
  background: "#1a120e",
  foreground: "#faeee5",
  card: "#241a15",
  "card-foreground": "#faeee5",
  popover: "#201712",
  "popover-foreground": "#faeee5",
  primary: "#e28a61",
  "primary-foreground": "#1a120e",
  secondary: "#30231c",
  "secondary-foreground": "#faeee5",
  muted: "#34261f",
  "muted-foreground": "#d1bdb0",
  accent: "#83abc4",
  "accent-foreground": "#111a20",
  destructive: "#e27670",
  border: "#49362c",
  input: "#543e32",
  ring: "#e28a61",
  "chart-1": "#e28a61",
  "chart-2": "#83abc4",
  "chart-3": "#e7c4af",
  "chart-4": "#bd704e",
  "chart-5": "#6f91a6",
  sidebar: "#201712",
  "sidebar-foreground": "#faeee5",
  "sidebar-primary": "#e28a61",
  "sidebar-primary-foreground": "#1a120e",
  "sidebar-accent": "#302822",
  "sidebar-accent-foreground": "#faeee5",
  "sidebar-border": "#49362c",
  "sidebar-ring": "#e28a61",
  "secondary-offset": "#201712",
  surface: "#201712",
  "surface-foreground": "#dbc9bd",
  code: "#201712",
  "code-foreground": "#dbc9bd",
  "code-highlight": "#31251f",
  "code-number": "#e28a61",
  selection: "#f2d4c2",
  "selection-foreground": "#1a120e",
  "message-user": "#a54e2c",
  "message-user-foreground": "#ffffff",
};

const irisLight: PaletteTokens = {
  background: "#fbf8ff",
  foreground: "#281d31",
  card: "#f1ebf8",
  "card-foreground": "#281d31",
  popover: "#fdfbff",
  "popover-foreground": "#281d31",
  primary: "#67468e",
  "primary-foreground": "#ffffff",
  secondary: "#ece4f3",
  "secondary-foreground": "#382942",
  muted: "#eee7f3",
  "muted-foreground": "#66586e",
  accent: "#98556f",
  "accent-foreground": "#ffffff",
  destructive: "#a43c4a",
  border: "#d9cde3",
  input: "#d2c4de",
  ring: "#76549a",
  "chart-1": "#67468e",
  "chart-2": "#98556f",
  "chart-3": "#786283",
  "chart-4": "#a28ab5",
  "chart-5": "#bd7892",
  sidebar: "#f5effa",
  "sidebar-foreground": "#281d31",
  "sidebar-primary": "#67468e",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#eee3ed",
  "sidebar-accent-foreground": "#281d31",
  "sidebar-border": "#d9cde3",
  "sidebar-ring": "#76549a",
  "secondary-offset": "#f8f3fc",
  surface: "#f8f3fc",
  "surface-foreground": "#382942",
  code: "#f5f0f9",
  "code-foreground": "#382942",
  "code-highlight": "#e9dff0",
  "code-number": "#67468e",
  selection: "#4d3568",
  "selection-foreground": "#ffffff",
  "message-user": "#67468e",
  "message-user-foreground": "#ffffff",
};

const irisDark: PaletteTokens = {
  background: "#17111c",
  foreground: "#f5edf9",
  card: "#211728",
  "card-foreground": "#f5edf9",
  popover: "#1d1423",
  "popover-foreground": "#f5edf9",
  primary: "#b99bde",
  "primary-foreground": "#17111c",
  secondary: "#2b2032",
  "secondary-foreground": "#f5edf9",
  muted: "#302338",
  "muted-foreground": "#cfbdd7",
  accent: "#dc91ad",
  "accent-foreground": "#211018",
  destructive: "#e47782",
  border: "#46354f",
  input: "#503c5a",
  ring: "#b99bde",
  "chart-1": "#b99bde",
  "chart-2": "#dc91ad",
  "chart-3": "#ddcbe6",
  "chart-4": "#9479b1",
  "chart-5": "#b7728c",
  sidebar: "#1d1423",
  "sidebar-foreground": "#f5edf9",
  "sidebar-primary": "#b99bde",
  "sidebar-primary-foreground": "#17111c",
  "sidebar-accent": "#302337",
  "sidebar-accent-foreground": "#f5edf9",
  "sidebar-border": "#46354f",
  "sidebar-ring": "#b99bde",
  "secondary-offset": "#1d1423",
  surface: "#1d1423",
  "surface-foreground": "#d8c7df",
  code: "#1d1423",
  "code-foreground": "#d8c7df",
  "code-highlight": "#2d2134",
  "code-number": "#b99bde",
  selection: "#eadcf0",
  "selection-foreground": "#17111c",
  "message-user": "#7650a0",
  "message-user-foreground": "#ffffff",
};

export const PALETTE_FAMILIES: readonly PaletteFamily[] = [
  {
    id: "lumi",
    label: "Lumi",
    description: "Warm paper with amber and teal",
    light: lumiLight,
    dark: lumiDark,
  },
  {
    id: "graphite",
    label: "Graphite",
    description: "Crisp neutrals with steel blue",
    light: graphiteLight,
    dark: graphiteDark,
  },
  {
    id: "harbor",
    label: "Harbor",
    description: "Cool blue with seafoam",
    light: harborLight,
    dark: harborDark,
  },
  {
    id: "juniper",
    label: "Juniper",
    description: "Sage and evergreen with ochre",
    light: juniperLight,
    dark: juniperDark,
  },
  {
    id: "ember",
    label: "Ember",
    description: "Warm sand with terracotta",
    light: emberLight,
    dark: emberDark,
  },
  {
    id: "iris",
    label: "Iris",
    description: "Lavender with dusty rose",
    light: irisLight,
    dark: irisDark,
  },
] as const;

export const PALETTES_BY_ID = Object.fromEntries(
  PALETTE_FAMILIES.map((palette) => [palette.id, palette])
) as Record<PaletteId, PaletteFamily>;

export function isPaletteId(value: unknown): value is PaletteId {
  return typeof value === "string" && PALETTE_IDS.includes(value as PaletteId);
}

export function parsePalettePreferences(value: unknown): PalettePreferences {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return { ...DEFAULT_PALETTE_PREFERENCES };
  }

  const candidate = value as { light?: unknown; dark?: unknown };
  return {
    light: isPaletteId(candidate.light)
      ? candidate.light
      : DEFAULT_PALETTE_PREFERENCES.light,
    dark: isPaletteId(candidate.dark)
      ? candidate.dark
      : DEFAULT_PALETTE_PREFERENCES.dark,
  };
}

export function parseStoredPalettePreferences(
  value: string | null
): PalettePreferences {
  if (!value) return { ...DEFAULT_PALETTE_PREFERENCES };
  try {
    return parsePalettePreferences(JSON.parse(value));
  } catch {
    return { ...DEFAULT_PALETTE_PREFERENCES };
  }
}

export function getPaletteTokens(id: PaletteId, mode: PaletteMode) {
  return PALETTES_BY_ID[id][mode];
}

export function paletteTokenVariable(mode: PaletteMode, token: PaletteTokenName) {
  return `--palette-${mode}-${token}`;
}

export function applyPalettePreferencesToElement(
  element: HTMLElement,
  preferences: PalettePreferences
) {
  element.dataset.lightPalette = preferences.light;
  element.dataset.darkPalette = preferences.dark;

  for (const mode of ["light", "dark"] as const) {
    const tokens = getPaletteTokens(preferences[mode], mode);
    for (const token of PALETTE_TOKEN_NAMES) {
      element.style.setProperty(paletteTokenVariable(mode, token), tokens[token]);
    }
  }
}

export function serializePalettePreferences(preferences: PalettePreferences) {
  return JSON.stringify(preferences);
}

