import {
  googleWorkspaceOperationDescriptor,
  type GoogleWorkspaceOperation,
} from "../../src/apps/googleWorkspace.js";
import { createRuntimeFailure } from "../../src/runtime/RuntimeFailure.js";
import type { SharedToolContext, SharedToolDefinition, SharedToolModule } from "../contracts.js";
import { parseObjectInput } from "../helpers.js";

function createGoogleWorkspaceTool(options: { name: string; displayName: string; description: string; operation: GoogleWorkspaceOperation; inputSchema: Record<string, unknown>; readOnly: boolean }): SharedToolModule {
  const operation = googleWorkspaceOperationDescriptor(options.operation);
  const readOnly = operation.sideEffect === "read";
  if (options.name !== operation.desktopToolName || options.readOnly !== readOnly) {
    throw new Error(
      `Google Workspace tool '${options.name}' must match its canonical operation descriptor.`,
    );
  }
  const definition: SharedToolDefinition = {
    name: options.name, description: options.description, inputSchema: options.inputSchema,
    capability: { freshnessClass: "live", latencyClass: "medium", costClass: "free", executionClass: readOnly ? "read_only" : "external_side_effect", ...(readOnly ? {} : { allowedInteractionModes: ["chat", "build"] }), capabilityClasses: ["google.calendar", "network.call"], approvalCapabilities: ["network.call", ...(readOnly ? [] : (["external.confirm"] as const))] },
    presentation: { displayName: options.displayName, aliases: [options.displayName.toLowerCase()], keywords: ["google workspace", "calendar", options.operation], provider: "google-calendar", toolFamily: "calendar" },
  };
  return { definition, createHandler(context: SharedToolContext) { return async (input: unknown) => { if (!context.googleWorkspaceService) throw createRuntimeFailure("GOOGLE_WORKSPACE_NOT_CONNECTED", "Google Workspace is not connected in Kestrel Desktop.", { subsystem: "tooling", classification: "configuration", recoverable: true }); const threadId = context.runtime?.threadId ?? context.runtime?.sessionId; return await context.googleWorkspaceService.invoke(operation.serviceOperation, parseObjectInput(options.name, input), { ...(context.workspace?.appRoot === undefined ? {} : { cursorScope: context.workspace.appRoot }), ...(threadId === undefined ? {} : { threadId }) }); }; } };
}

const eventTime = { oneOf: [{ type: "object", properties: { dateTime: { type: "string", format: "date-time" }, timeZone: { type: "string" } }, required: ["dateTime"], additionalProperties: false }, { type: "object", properties: { date: { type: "string", format: "date" } }, required: ["date"], additionalProperties: false }] };
const eventFields = { summary: { type: "string", minLength: 1, maxLength: 1024 }, description: { type: "string", maxLength: 8192 }, location: { type: "string", maxLength: 1024 }, start: eventTime, end: eventTime, attendees: { type: "array", maxItems: 100, items: { type: "object", properties: { email: { type: "string", format: "email" }, displayName: { type: "string" } }, required: ["email"], additionalProperties: false } } };

export const googleWorkspaceListEventsTool = createGoogleWorkspaceTool({ name: "google_workspace.list_events", displayName: "Google Calendar List Events", description: "List events on the connected user's primary Google Calendar.", operation: "events.list", readOnly: true, inputSchema: { type: "object", properties: { timeMin: { type: "string", format: "date-time" }, timeMax: { type: "string", format: "date-time" }, cursor: { type: "string", minLength: 1, maxLength: 4096 }, maxResults: { type: "integer", minimum: 1, maximum: 100, default: 50 } }, required: ["timeMin", "timeMax"], additionalProperties: false } });
export const googleWorkspaceCreateEventTool = createGoogleWorkspaceTool({ name: "google_workspace.create_event", displayName: "Google Calendar Create Event", description: "Create an event on the connected user's primary calendar after approval.", operation: "events.create", readOnly: false, inputSchema: { type: "object", properties: { event: { type: "object", properties: eventFields, required: ["summary", "start", "end"], additionalProperties: false }, notifyAttendees: { type: "boolean", default: false } }, required: ["event"], additionalProperties: false } });
export const googleWorkspaceUpdateEventTool = createGoogleWorkspaceTool({ name: "google_workspace.update_event", displayName: "Google Calendar Update Event", description: "Update an event on the connected user's primary calendar after approval.", operation: "events.update", readOnly: false, inputSchema: { type: "object", properties: { eventId: { type: "string", minLength: 1 }, patch: { type: "object", properties: eventFields, minProperties: 1, additionalProperties: false }, notifyAttendees: { type: "boolean", default: false } }, required: ["eventId", "patch"], additionalProperties: false } });
export const googleWorkspaceDeleteEventTool = createGoogleWorkspaceTool({ name: "google_workspace.delete_event", displayName: "Google Calendar Delete Event", description: "Delete an event from the connected user's primary calendar after approval.", operation: "events.delete", readOnly: false, inputSchema: { type: "object", properties: { eventId: { type: "string", minLength: 1 }, notifyAttendees: { type: "boolean", default: false } }, required: ["eventId"], additionalProperties: false } });
export const googleWorkspaceSearchGmailTool = createGoogleWorkspaceTool({ name: "google_workspace.search_gmail", displayName: "Gmail Search Messages", description: "Search the connected user's Gmail using the exact native Gmail query supplied.", operation: "gmail.messages.search", readOnly: true, inputSchema: { type: "object", properties: { query: { type: "string", minLength: 1, maxLength: 4096 }, cursor: { type: "string", minLength: 1, maxLength: 4096 }, maxResults: { type: "integer", minimum: 1, maximum: 100, default: 50 } }, required: ["query"], additionalProperties: false } });
export const googleWorkspaceGetGmailMessageTool = createGoogleWorkspaceTool({ name: "google_workspace.get_gmail_message", displayName: "Gmail Get Message", description: "Read one selected Gmail message. Attachment bytes are never returned.", operation: "gmail.messages.get", readOnly: true, inputSchema: { type: "object", properties: { messageId: { type: "string", minLength: 1, maxLength: 1024 } }, required: ["messageId"], additionalProperties: false } });
export const googleWorkspaceGetGmailThreadTool = createGoogleWorkspaceTool({ name: "google_workspace.get_gmail_thread", displayName: "Gmail Get Thread", description: "Read one selected native Gmail thread. Attachment bytes are never returned.", operation: "gmail.threads.get", readOnly: true, inputSchema: { type: "object", properties: { threadId: { type: "string", minLength: 1, maxLength: 1024 } }, required: ["threadId"], additionalProperties: false } });
export const googleWorkspaceImportGmailAttachmentTool = createGoogleWorkspaceTool({ name: "google_workspace.import_gmail_attachment", displayName: "Gmail Import Attachment", description: "Import one selected Gmail attachment into the current Thread file store. Attachment bytes are never returned to the model.", operation: "gmail.attachments.import", readOnly: true, inputSchema: { type: "object", properties: { messageId: { type: "string", minLength: 1, maxLength: 1024 }, attachmentId: { type: "string", minLength: 1, maxLength: 1024 } }, required: ["messageId", "attachmentId"], additionalProperties: false } });
export const googleWorkspaceSendGmailTool = createGoogleWorkspaceTool({ name: "google_workspace.send_gmail", displayName: "Gmail Send Message", description: "Send Gmail only after approval of the exact recipients, content, and Thread-file revisions.", operation: "gmail.messages.send", readOnly: false, inputSchema: { type: "object", properties: { to: { type: "array", minItems: 1, maxItems: 50, items: { type: "string", format: "email" } }, cc: { type: "array", maxItems: 50, items: { type: "string", format: "email" }, default: [] }, subject: { type: "string", minLength: 1, maxLength: 998 }, text: { type: "string", minLength: 1, maxLength: 100000 }, html: { type: "string", minLength: 1, maxLength: 200000 }, attachmentFileIds: { type: "array", maxItems: 20, items: { type: "string", minLength: 1, maxLength: 1024 }, default: [] }, __kestrelGmailPrepared: { type: "object", properties: {}, additionalProperties: true } }, required: ["to", "subject", "text"], additionalProperties: false } });
export const googleWorkspaceReplyGmailTool = createGoogleWorkspaceTool({ name: "google_workspace.reply_gmail", displayName: "Gmail Reply Message", description: "Reply to a selected Gmail message after exact approval. Gmail resolves the recipient, subject, thread, and RFC reply headers.", operation: "gmail.messages.reply", readOnly: false, inputSchema: { type: "object", properties: { messageId: { type: "string", minLength: 1, maxLength: 1024 }, text: { type: "string", minLength: 1, maxLength: 100000 }, html: { type: "string", minLength: 1, maxLength: 200000 }, attachmentFileIds: { type: "array", maxItems: 20, items: { type: "string", minLength: 1, maxLength: 1024 }, default: [] }, __kestrelGmailPrepared: { type: "object", properties: {}, additionalProperties: true } }, required: ["messageId", "text"], additionalProperties: false } });
