import type { GoogleWorkspaceOperation } from "../../src/apps/googleWorkspace.js";
import { createRuntimeFailure } from "../../src/runtime/RuntimeFailure.js";
import type { SharedToolContext, SharedToolDefinition, SharedToolModule } from "../contracts.js";
import { parseObjectInput } from "../helpers.js";

function createGoogleWorkspaceTool(options: { name: string; displayName: string; description: string; operation: GoogleWorkspaceOperation; inputSchema: Record<string, unknown>; readOnly: boolean }): SharedToolModule {
  const definition: SharedToolDefinition = {
    name: options.name, description: options.description, inputSchema: options.inputSchema,
    capability: { freshnessClass: "live", latencyClass: "medium", costClass: "free", executionClass: options.readOnly ? "read_only" : "external_side_effect", ...(options.readOnly ? {} : { allowedInteractionModes: ["chat", "build"] }), capabilityClasses: ["google.calendar", "network.call"], approvalCapabilities: ["network.call", ...(options.readOnly ? [] : (["external.confirm"] as const))] },
    presentation: { displayName: options.displayName, aliases: [options.displayName.toLowerCase()], keywords: ["google workspace", "calendar", options.operation], provider: "google-calendar", toolFamily: "calendar" },
  };
  return { definition, createHandler(context: SharedToolContext) { return async (input: unknown) => { if (!context.googleWorkspaceService) throw createRuntimeFailure("GOOGLE_WORKSPACE_NOT_CONNECTED", "Google Workspace is not connected in Kestrel Desktop.", { subsystem: "tooling", classification: "configuration", recoverable: true }); return await context.googleWorkspaceService.invoke(options.operation, parseObjectInput(options.name, input)); }; } };
}

const eventTime = { oneOf: [{ type: "object", properties: { dateTime: { type: "string", format: "date-time" }, timeZone: { type: "string" } }, required: ["dateTime"], additionalProperties: false }, { type: "object", properties: { date: { type: "string", format: "date" } }, required: ["date"], additionalProperties: false }] };
const eventFields = { summary: { type: "string", minLength: 1, maxLength: 1024 }, description: { type: "string", maxLength: 8192 }, location: { type: "string", maxLength: 1024 }, start: eventTime, end: eventTime, attendees: { type: "array", maxItems: 100, items: { type: "object", properties: { email: { type: "string", format: "email" }, displayName: { type: "string" } }, required: ["email"], additionalProperties: false } } };

export const googleWorkspaceListEventsTool = createGoogleWorkspaceTool({ name: "google_workspace.list_events", displayName: "Google Calendar List Events", description: "List events on the connected user's primary Google Calendar.", operation: "events.list", readOnly: true, inputSchema: { type: "object", properties: { timeMin: { type: "string", format: "date-time" }, timeMax: { type: "string", format: "date-time" }, maxResults: { type: "integer", minimum: 1, maximum: 100, default: 50 } }, required: ["timeMin", "timeMax"], additionalProperties: false } });
export const googleWorkspaceCreateEventTool = createGoogleWorkspaceTool({ name: "google_workspace.create_event", displayName: "Google Calendar Create Event", description: "Create an event on the connected user's primary calendar after approval.", operation: "events.create", readOnly: false, inputSchema: { type: "object", properties: { event: { type: "object", properties: eventFields, required: ["summary", "start", "end"], additionalProperties: false }, notifyAttendees: { type: "boolean", default: false } }, required: ["event"], additionalProperties: false } });
export const googleWorkspaceUpdateEventTool = createGoogleWorkspaceTool({ name: "google_workspace.update_event", displayName: "Google Calendar Update Event", description: "Update an event on the connected user's primary calendar after approval.", operation: "events.update", readOnly: false, inputSchema: { type: "object", properties: { eventId: { type: "string", minLength: 1 }, patch: { type: "object", properties: eventFields, minProperties: 1, additionalProperties: false }, notifyAttendees: { type: "boolean", default: false } }, required: ["eventId", "patch"], additionalProperties: false } });
export const googleWorkspaceDeleteEventTool = createGoogleWorkspaceTool({ name: "google_workspace.delete_event", displayName: "Google Calendar Delete Event", description: "Delete an event from the connected user's primary calendar after approval.", operation: "events.delete", readOnly: false, inputSchema: { type: "object", properties: { eventId: { type: "string", minLength: 1 }, notifyAttendees: { type: "boolean", default: false } }, required: ["eventId"], additionalProperties: false } });
