export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_TURN_ID =
  "deployment-canary-turn-attachment-v1";
export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_FILE_ID =
  "deployment-canary-file-v1";
export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_FILENAME =
  "turn-attachment-canary-v1.txt";
export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_MEDIA_TYPE = "text/plain";
export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_TEXT =
  "KESTREL_TURN_ATTACHMENT_DEPLOYMENT_CANARY_V1\n";
export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_SIZE_BYTES = 45;
export const TURN_ATTACHMENT_DEPLOYMENT_CANARY_SHA256 =
  "44801d373a198aea408c2d6fa6c0de05682d2a7ac7729f711e698352ab1948ff";
