export const HOSTED_BROWSER_VIEWER_RAW_PNG_MAX_BYTES = 20 * 1024 * 1024;

const HOSTED_BROWSER_VIEWER_FRAME_JSON_OVERHEAD_BYTES = 8 * 1024;

export const HOSTED_BROWSER_VIEWER_MAX_SERIALIZED_FRAME_BYTES =
  4 * Math.ceil(HOSTED_BROWSER_VIEWER_RAW_PNG_MAX_BYTES / 3) +
  HOSTED_BROWSER_VIEWER_FRAME_JSON_OVERHEAD_BYTES;
