export type TransitionStatus = "RUNNING" | "WAITING" | "COMPLETED" | "FAILED";
export type EffectFailurePolicy = "STOP" | "CONTINUE" | "WAIT";
export type EffectExecutionStatus = "PENDING" | "DONE" | "FAILED";
export type OutboxStatus = "PENDING" | "DELIVERED" | "FAILED";
export type ClaimStatus = "proposed" | "verified" | "disputed" | "retracted";
export type RunEventLevel = "INFO" | "WARN" | "ERROR";
export type RunEventType =
  | "run.started"
  | "run.resumed"
  | "run.waiting"
  | "run.completed"
  | "run.failed"
  | "run.cancelled"
  | "run.tool.started"
  | "run.tool.completed"
  | "run.tool.failed"
  | "turn.started"
  | "turn.segment"
  | "turn.completed"
  | "normalized.failure"
  | "terminal.normalized"
  | "step.selected"
  | "step.started"
  | "step.committed"
  | "step.transitioned"
  | "step.contract_failed"
  | "effects.resumed"
  | "effects.executed"
  | "outbox.dispatched"
  | "policy.checkpoint"
  | "quality.computed"
  | "progress.stage"
  | "progress.tool"
  | "progress.waiting"
  | "progress.heartbeat"
  | "reasoning.update"
  | "tool.queue.enqueued"
  | "tool.queue.dequeued"
  | "tool.queue.overflow"
  | "tool.validated"
  | "tool.chunk.started"
  | "tool.chunk.completed"
  | "tool.result_summarized"
  | "tool.retry"
  | "model.requested"
  | "model.provenance"
  | "model.completed"
  | "decision.generated"
  | "decision.compiled"
  | "decision.policy_passed"
  | "decision.rejected"
  | "decision.redirected"
  | "decision.executed"
  | "route.decision"
  | "route.override"
  | "resolver.generated"
  | "resolver.rejected"
  | "resolver.bypassed"
  | "planner.tool_intent_promoted"
  | "planner.finalize_blocked"
  | "mode.legacy_migrated"
  | "clarification.triggered"
  | "progress.blocked"
  | "region.scheduled"
  | "region.started"
  | "region.completed"
  | "region.synced"
  | "region.merge_conflict"
  | "region.scheduler.claimed"
  | "region.scheduler.spawned"
  | "region.scheduler.synced"
  | "region.scheduler.waiting"
  | "wait.entered"
  | "wait.resumed"
  | "run.continuation_requested"
  | "run.continuation_granted"
  | "run.continuation_declined"
  | "context.compaction_armed"
  | "context.compaction_applied"
  | "context.adaptation_applied"
  | "context.compaction_suppressed"
  | "interaction.requested"
  | "interaction.resolved"
  | "approval.granted"
  | "operator.steered"
  | "context.checkpoint_requested"
  | "context.checkpoint_auto_resolved"
  | "context.checkpoint_resolved"
  | "runtime.assembly.changed"
  | "runtime.state_persisted"
  | "runtime.resume_blocked"
  | "delegation.requested"
  | "delegation.spawned"
  | "delegation.progress"
  | "delegation.waiting"
  | "delegation.completed"
  | "delegation.failed"
  | "delegation.superseded"
  | "delegation.reconciled"
  | "workspace.checkpoint_captured"
  | "workspace.checkpoint_restored"
  | "workspace.checkpoint_cleaned"
  | "workspace.checkpoint_cleanup_failed"
  | "workspace.promotion_recorded"
  | "workspace.promotion_undo_restored"
  | "managed_worktree.approval_requested"
  | "managed_worktree.auto_requested"
  | "managed_worktree.created"
  | "managed_worktree.reused"
  | "managed_worktree.orphan_detected"
  | "managed_worktree.orphan_reclaimed"
  | "managed_worktree.rotated"
  | "managed_worktree.blocked"
  | "managed_worktree.bound"
  | "managed_worktree.leased"
  | "managed_worktree.lease_blocked"
  | "managed_worktree.released"
  | "managed_worktree.process_attached"
  | "managed_worktree.process_released"
  | "managed_worktree.fan_in_candidate"
  | "managed_worktree.fan_in_applied"
  | "managed_worktree.promotion_candidate"
  | "managed_worktree.promoted"
  | "managed_worktree.promotion_blocked"
  | "managed_worktree.promotion_skipped"
  | "managed_worktree.promotion_undo_restored"
  | "loop.guard_triggered"
  | "loop.stall_detected"
  | "loop.stall_converted"
  | "loop.stall_resumed"
  | "migration.session_archived"
  | "migration.session_migrated";

export interface RuntimeError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface ToolIntent {
  mode: "prefer_named_tool";
  rawMention: string;
  preferenceStrength: "strong";
}

export interface StateNodeRef {
  parent: string;
  child: string;
  region?: string | undefined;
}
